# Generated by Django 3.1.5 on 2021-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerbiometric',
            name='face_pic',
            field=models.ImageField(blank=True, null=True, upload_to='faces/%Y/%m/%d/'),
        ),
    ]
