# Generated by Django 3.1.5 on 2021-02-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210212_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerbiometric',
            name='name',
            field=models.CharField(default='face_image', max_length=30),
        ),
        migrations.AlterField(
            model_name='workerbiometric',
            name='date_stored',
            field=models.DateField(verbose_name='date saved'),
        ),
        migrations.AlterField(
            model_name='workerbiometric',
            name='face_pic',
            field=models.FileField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
