# Generated by Django 3.1.5 on 2021-02-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerbiometric',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
