# Generated by Django 3.1.5 on 2021-02-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_workerbiometric_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerbiometric',
            options={'ordering': ['person']},
        ),
    ]
