# Generated by Django 3.1.5 on 2021-02-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Enter username', max_length=30)),
                ('user_pass', models.CharField(help_text='Enter your password', max_length=20)),
            ],
            options={
                'ordering': ['user_name'],
            },
        ),
    ]
