# Generated by Django 3.1.5 on 2021-05-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='filename',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
