# Generated by Django 3.1.5 on 2021-05-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_documents_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documents',
            name='permission',
            field=models.IntegerField(default=0),
        ),
    ]
