# Generated by Django 3.1.5 on 2021-05-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_auto_20210520_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
